# Generated by Django 4.2.5 on 2023-10-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CashTrackApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='accountNumber',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='name',
            new_name='fullName',
        ),
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default='dead', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='userName',
            field=models.CharField(default='your_default_value', max_length=100),
            preserve_default=False,
        ),
    ]
